### ISSUE TITLE
Synology Docker

### ISSUE THREAD

**Issue by rzrhome** [brycelarge/xteve-vpn#1]
i run the container on a synology nas, but openvpn will not connect over the vpn. `curl ifconfig.me´shows only my real network ip. i testet all with surfshark and goosevpn but i become no connection over the vpn.

https://registry.hub.docker.com/r/binhex/arch-delugevpn/ works with no issues and the vpn connection works fine here.

**Comment by brycelarge** [comment]
Hi, could you supply me with the run script? Also there is a container debug env variable you can use to get a little more out of the logs for debugging -e DEBUG='true'

I don't have synology server to use to test but I'm sure we can figure this out.

**Comment by provosta99** [comment]
Hi, i'm using unraid and i'm trying tu use auth-user-pass in ovpn file but i got an error "cannot stat file secret"
my path is good and i tried full path also. Any idea?

**Comment by brycelarge** [comment]
> Hi, i'm using unraid and i'm trying tu use auth-user-pass in ovpn file but i got an error "cannot stat file secret"
> my path is good and i tried full path also. Any idea?

Hi, if your using unraid did you install using community applications? The username and password you pass in as environment variables.

Which vpn provider are you using as the container has PIA and Surfshark built in?

**Comment by brycelarge** [comment]
> Hi, i'm using unraid and i'm trying tu use auth-user-pass in ovpn file but i got an error "cannot stat file secret"
> my path is good and i tried full path also. Any idea?

I have just made a change which will clean any custom ovpn you use so t does not conflict with the start up script, this should fix your issue.

**Comment by brycelarge** [comment]
> i run the container on a synology nas, but openvpn will not connect over the vpn. `curl ifconfig.me´shows only my real network ip. i testet all with surfshark and goosevpn but i become no connection over the vpn.
> 
> https://registry.hub.docker.com/r/binhex/arch-delugevpn/ works with no issues and the vpn connection works fine here.

Use the following environment variable: -e CREATE_TUN_DEVICE=true

Let me know if that works?

**Comment by rzrhome** [comment]
surfshark works great now, but i cant connect to goosevpn and many more vpn´s over the custom setting :/ some usernames are the email adresses. if you want i can share 1-2 accounts with you

**Comment by brycelarge** [comment]
> surfshark works great now, but i cant connect to goosevpn and many more vpn´s over the custom setting :/ some usernames are the email adresses. if you want i can share 1-2 accounts with you

Yes please, that will help me out. I opened a discord server to make it easier to chat. https://discord.gg/fjUX2Uz9

**Comment by brycelarge** [comment]
Issue has been resolved, closing issue
