### ISSUE TITLE
Not working OpenVPN and news updates

### ISSUE THREAD

**Issue by ruiribeiro2020** [brycelarge/xteve-vpn#11]
Hello,
all good?

I did the installation in unraid, I inserted the ovpn file and the login data, but when I do the speedtest my ip always appears without vpn.

Can you add an option that shows you are connected to the VPN?

I would also like to know if you can update this system to a newer version with new features and updates to use with emby, jellyfin, etc.

**Comment by brycelarge** [comment]
Hi there, I do have plans to update the app but day job has me rather busy of late. Look through the docker logs to see what the issues are, there is also a debug mode which will give you more information in the logs.

**Comment by ruiribeiro2020** [comment]
Hi, Okay, good, that's good news.

As for logs and analysis, I don't have much experience yet, but I'll try.

Is there any option you can add, so that 1 stream can be seen by multiple users? or else have another option for users to only see the channel that is playing and not be able to click to open another one?

Thanks in advance for your contribution.
