### ISSUE TITLE
Noticed a few things after an update

### ISSUE THREAD

**Issue by jsbear** [brycelarge/xteve-vpn#12]
Waiting for VPN & Privoxy, I'm routing through another container with VPN, so I don't need to utilize the VPN feature anymore.  Was working great until today.

2023-03-15 17:32:38 [xTeVe] [ERROR] stat /usr/bin/ffmpeg: no such file or directory () - EC: 0

Switched settings from ffmpeg to xteve, working now ...

**Comment by brycelarge** [comment]
Hi, apologies. I have been working on upgrades and broke a few things.  
Set your ffmpeg binary path to /usr/lib/jellyfin-ffmpeg/ffmpeg

**Comment by jsbear** [comment]
> Hi, apologies. I have been working on upgrades and broke a few things. Set your ffmpeg binary path to /usr/lib/jellyfin-ffmpeg/ffmpeg

That worked thank you, appreciate the upgrades :)

**Comment by brycelarge** [comment]
privoxy and nvidea hardware acceleration are being added, will update the docs once I have tested everything
