### ISSUE TITLE
Under Plex, Channel Sources, My Guide

### ISSUE THREAD

**Issue by jsbear** [brycelarge/xteve-vpn#13]
Showing "device not found", even though I can still refresh the guide in Plex.  Maybe some kind of firewall / routing / discovery issue?  I have not tried to remove and re-add the device yet.

**Comment by jsbear** [comment]
Seems to be working now, strange ...  I will follow-up if needed.

**Comment by brycelarge** [comment]
Plex does that sometimes when xteve is restarted. Sometimes restarting plex fixes the issue but othertimes just remove the dvr restart plex and re-add the dvr.

Can I ask which vpn provider you use?

**Comment by jsbear** [comment]
I use NordVPN.

Have you considered updating xTeve with some of the more active forks?  Seems like development on main branch ended several years ago.

**Comment by brycelarge** [comment]
have you tried any?On 18 Mar 2023, at 00:23, jsbear ***@***.***> wrote:﻿
I use NordVPN.
Have you considered updating xTeve with some of the more active forks?  Seems like development on main branch ended several years ago.
