### ISSUE TITLE
Heyo

### ISSUE THREAD

**Issue by Jakethesnkae** [brycelarge/xteve-vpn#14]
I'm not sure if this a bug i'm unsure what to do as i've tried changing stuff around 

"Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/88.ovpn:9: data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-cipherssssssssssssssssss (2.5.5) "

this keeps popping up, i'm using torguard

**Comment by brycelarge** [comment]
Can you download a fresh config file from torguard and supply me with that so I can test?

 

 

Kind Regards

Bryce

 

 

From: Jakethesnkae ***@***.***>
Reply to: brycelarge/xteve-vpn ***@***.***>
Date: Friday, 17 March 2023 at 09:43
To: brycelarge/xteve-vpn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [brycelarge/xteve-vpn] Heyo (Issue #14)

 

I'm not sure if this a bug i'm unsure what to do as i've tried changing stuff around

"Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/88.ovpn:9: data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-data-cipherssssssssssssssssss (2.5.5) "

this keeps popping up, i'm using torguard

**Comment by Jakethesnkae** [comment]
[49.zip](https://github.com/brycelarge/xteve-vpn/files/11000897/49.zip)

Here's a fresh config file from torguard
