### ISSUE TITLE
The script that download the Surfshark conf doesn't work

### ISSUE THREAD

**Issue by PilaScat** [brycelarge/xteve-vpn#17]
Like in the title

**Comment by brycelarge** [comment]
Hi there, it works for me. You would need to supply full logs and what operating system you are running the docker on?

**Comment by PilaScat** [comment]
ok now it downloads the conf files but it doesn't use them
unraid, here the logs:
![image](https://user-images.githubusercontent.com/12989749/230040034-837112cd-91d3-41a8-b814-915bbda0a980.png)

**Comment by brycelarge** [comment]
You’re not specifying the config to use.  -e OPENVPN_CONFIG

**Comment by PilaScat** [comment]
![image](https://user-images.githubusercontent.com/12989749/230063013-6678ea83-8ad9-4821-a34f-649928383999.png)
![image](https://user-images.githubusercontent.com/12989749/230063184-7c1033d5-c541-4955-8c64-2bb111949d3e.png)

maybe its the template that is incorrect?

**Comment by brycelarge** [comment]
I’m not sure then. What I can say from looking at your screen shots is the unraid template does not look like my version. Perhaps it’s been modified or something gone wrong with it. Switch to advanced view and at the top there should be a red x you hat you can use to delete it and then reinstall and see if that fixes it

**Comment by PilaScat** [comment]
For now I dropped some VPN server in the openvpn folder, I already configured xteve, it's the third time, for now I'm ok with thisFilippo Scatigna On 5 Apr 2023 17:53, Bryce Large ***@***.***> wrote:
I’m not sure then. What I can say from looking at your screen shots is the unraid template does not look like my version. Perhaps it’s been modified or something gone wrong with it. Switch to advanced view and at the top there should be a red x you hat you can use to delete it and then reinstall and see if that fixes it
