### ISSUE TITLE
unRAID and NordVPN

### ISSUE THREAD

**Issue by provosta99** [brycelarge/xteve-vpn#2]
Hello, I moved the conversation here, i realized that i was in another conversation! Sorry about that.
I am using unRAID and I am trying to use auth-user-pass in ovpn file but I have a "could not stat secret file" error
my path is good and i also tried the full path. An idea?

I installed it with community apps
I am using NordVPN
I redeployed it this morning and I have the same problem.
Since I put the username / password in an external file, I left the values ​​blank for these items.

**Comment by brycelarge** [comment]
NordVPN is a bit more complicated than PIA and Surfshark. Let me see if I can get a small account with them and see what I can do. Little Overwhelmed at the moment as my first child was just born. But I'll have a look this weekend for you. Surfshark works really well if you have the funds to get a small account in the meantime.

**Comment by brycelarge** [comment]
> Hello, I moved the conversation here, i realized that i was in another conversation! Sorry about that.
> I am using unRAID and I am trying to use auth-user-pass in ovpn file but I have a "could not stat secret file" error
> my path is good and i also tried the full path. An idea?
> 
> I installed it with community apps
> I am using NordVPN
> I redeployed it this morning and I have the same problem.
> Since I put the username / password in an external file, I left the values ​​blank for these items.

Try removing auth from the file and putting the username and password in. My startup scripts are stripping these out and creating its own auth file and I think thats why its conflicting.

**Comment by brycelarge** [comment]
Hi, I opened a discord server to make it easier to chat. https://discord.gg/fjUX2Uz9

**Comment by brycelarge** [comment]
I just pushed a fix that could be causing the issue. 

My scripts are removing auth-user-pass and replacing it with auth-user-pass /config/openvpn/custom-openvpn-credentials.txt and within the custom-openvpn-credentials.txt file is the username and password that is passed in using the OPENVPN_USERNAME and OPENVPN_PASSWORD environment variables. So try that and let me know if it's working?

You would have to update the container to test if it works

**Comment by provosta99** [comment]
I have updated te container and be able to establish the connection to NordVPN. The only problem is that i'm not able to reach the WEBui of Xteve. I think that is related to the fact that NordVPN is not permitting port forwarding. What do you think? Do you encounter this problem with the others VPN?

**Comment by brycelarge** [comment]
> I have updated te container and be able to establish the connection to NordVPN. The only problem is that i'm not able to reach the WEBui of Xteve. I think that is related to the fact that NordVPN is not permitting port forwarding. What do you think? Do you encounter this problem with the others VPN

Yes that does happen. Have you filled in the LOCAL NETWORK variable? If your router IP address is 192.168.0.1 then you need to enter 192.168.0.0/24 and that will add the routes needed to reach the webui.

**Comment by provosta99** [comment]
Worked. I'm very happy, thank you very much!

**Comment by brycelarge** [comment]
> Worked. I'm very happy, thank you very much!

My pleasure, enjoy. Closing the issue
