### ISSUE TITLE
Question about buffer

### ISSUE THREAD

**Issue by rnegrette** [brycelarge/xteve-vpn#4]
Hi, sorry for submitting this as an issue, as it's really more of a question. With the alturismo/xteve_vpn docker, it's specifically called out that you need to use the buffer feature within xTeVe in order for the stream traffic to be handled by the VPN. Is that the same with your docker? I currently have yours up and running without any hiccups, but I'm still concerned about the messaging in the logs when no buffer is enabled:

`xTeVe is no longer involved, the client connects directly to the streaming server.`

If the client (a FireStick, for example) is connecting directly to the streaming server -- then is any of that stream traffic actually being routed over the VPN in your container? Thanks!

**Comment by brycelarge** [comment]
Hi There,

Yes that is correct. If xTeVe passes the URL onto the FireStick then the connection would be made through which ever internet connection the FireStick is using and not the VPN.

So all options use the VPN except the No Buffer option.
 
I have found best success with xTeVe buffer option, what happens is xTeVe will connect to the streaming server through the VPN and then pass the content to your FireStick.

**Comment by rnegrette** [comment]
Great, thanks for the clarification @brycelarge !!
