### ISSUE TITLE
Xteve cant connect to any streams through VPN

### ISSUE THREAD

**Issue by northernpowerhouse** [brycelarge/xteve-vpn#9]
I have a playlist which works absolutely fine in regular xteve (without VPN), xteve-vpn pulls the m3u perfectly, presents all the info to emby, but when i try to watch a channel, it throws a 404 error when trying to grab the stream. Without VPN, regular xteve behaves normally, connects FFMPEG to the same stream, remuxes it and sends to emby.

Speedtest can also happily connect to a server in the correct location. I've attached my environmentals below, any ideas?:

CREATE_TUN_DEVICE | true
DEBUG | false
HOME | /root
LANG | en_US.UTF-8
LANGUAGE | en_US.UTF-8
LOCAL_NETWORK | 192.168.1.0/24
NAME_SERVERS | 209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
OPENVPN_CONFIG | new_zealand
OPENVPN_OPTIONS |  
OPENVPN_PASSWORD | LOL
OPENVPN_PROTOCOL | udp
OPENVPN_PROVIDER | PIA
OPENVPN_USERNAME | LOL
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID | 1000
PUID | 1006
TERM | xterm
TZ | Europe/Lonon
UMASK | 000
XTEVE_BRANCH | master
XTEVE_DEBUG | 0
XTEVE_PORT | 34401

**Comment by northernpowerhouse** [comment]
update: I get the same behaviour from this docker when I remove the oVPN options and try and connect bareback, too. playlist updating is fine, byt not streaming

**Comment by brycelarge** [comment]
Hi,

That’s hard to answer without debug mode on and the logs. My guess would be a networking issue between emby and xteve vpn containers. Perhaps you can can also give the startup scripts for each docker container.

Also need to know what the urls are that emby is trying to connect to.

Kind Regards 
Bryce
